# <div class="alert alert-success" >(3) Array shape manipulation

Like the name suggest we will be looking at some functions that can change the shape of an array ie change number of elements per row, column and depth 

In [1]:
import numpy as np
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### <div class= "alert alert-info">Reshaping Array using reshape() method:
    
<span style="color:red"> reshape(newshape, order='C')</span>: Gives a new shape to an array without changing its data.

<ins>Parameters:</ins>
    
   - newshape:is an integer or tuple of ints. The new shape should be compatible with the original shape. If an integer, then the result       will be a 1-D array of that length. One shape dimension can be -1. In this case, the value is inferred from the length of       the array and remaining dimensions.

    
  - order{‘C’, ‘F’, ‘A’}: optional.Read the elements of a using this index order, and place the elements into the reshaped         array using this index order. ‘C’ means to read / write the elements using C-like index order, with the last axis index         changing fastest, back to the first axis index changing slowest. ‘F’ means to read / write the elements using Fortran-like     index order, with the first index changing fastest, and the last index changing slowest. Note that the ‘C’ and ‘F’ options     take no account of the memory layout of the underlying array, and only refer to the order of indexing. ‘A’ means to read /     write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.

<ins>Returns:</ins>
    
  -reshaped_arrayndarray:This will be a new view object if possible; otherwise, it will be a copy. Note there is no guarantee      of the memory layout(C- or Fortran- contiguous) of the returned array.

In [2]:
b = a.reshape(3,10)    #a.size = 30 so reshape to 2D array: r x c = 30 (3x10=30)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [3]:
c = a.reshape(3,2,5)   #a.size = 30 so reshape 3D: d x r x c = 30 (i.e 3x2x5=30)
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

<div class = "alert alert-warning"> if we cant figure out any ONE dimension for reshaping an array we can use ' -1 ' for that dimension. Numpy calculates it for us. I no such number exist it raise err:</div>

In [4]:
d= a.reshape(3,-1,5)
d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [5]:
d.shape

(3, 2, 5)

In [6]:
e = a.reshape(2,-1)
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [7]:
e.shape

(2, 15)

#### <div class= "alert alert-info">Reshaping  using shape() with tuple

In [8]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
a.shape = (5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [10]:
a.shape = (2,3,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

#### <div class= "alert alert-info">Flattening Array:
    
    Flattening an array means changing a multidimensional array to a 1D array(Vector).

#### (a).Using reshape() function:

In [11]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [12]:
aflat = a.reshape(-1)
aflat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### (b). Using flatten() function:

In [13]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [14]:
bflat = b.flatten()
bflat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### (a).Using ravel() function:

In [15]:
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [16]:
cflat = c.ravel()
cflat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
aflat == bflat

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [18]:
 bflat == cflat    # thus aflat == cflat

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

#### <div class= "alert alert-warning">Difference between flatten() & ravel()</div> 

- <mark>flatten():</mark>
    
    1. is a method of ndarray object
    2. slower then ravel()
    3. returns a copy of orignal array  (More on copy and view of array in next topic)
    4. modifying the resultant 1D arrayhas no effect on the orignal array

- <mark>ravel():</mark>

    1. is a library level function  
    2. is faster then flatten()
    3. returns only a refrence/view of the orignal array (More on copy and view of array in next topic)
    4. changing elements of resultant 1D array changes the orignal array


#### <div class= "alert alert-info">Changing array shape using transpose() function:
    
    T or transpose() interchanges rowas and columns in 2D array and in 3D array inderchanges dimension of depth with column and rows remains fixed

##### 1D

In [19]:
aa = np.arange(30)
aa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
bb = aa.T
bb

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

<div class= "alert alert-warning">1D array transpose is the same 1D array</div>

In [21]:
aa == bb

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

##### 2D

In [22]:
cc = aa.reshape(6,5)
cc

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [23]:
cc.transpose()

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

##### 3D

In [24]:
dd = aa.reshape(2,3,5)
dd

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [25]:
dd.T    # in 3D (d,r,c)^T = (d_new = c,r, c_new = d)

array([[[ 0, 15],
        [ 5, 20],
        [10, 25]],

       [[ 1, 16],
        [ 6, 21],
        [11, 26]],

       [[ 2, 17],
        [ 7, 22],
        [12, 27]],

       [[ 3, 18],
        [ 8, 23],
        [13, 28]],

       [[ 4, 19],
        [ 9, 24],
        [14, 29]]])

<div class= "alert alert-warning"> dd.T = [ [[d0c0 d1c0]] , [[d0c1 d1c1]] , [[d0c2 d1c2]] , [[d0c3 d1c3]] , [[d0c4 d1c4]] ] </div>

#### <div class= "alert alert-info">Changing array shape using resize() function:

In [26]:
aa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
aa.resize((6,5))
aa

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [32]:
aa.resize((3,2,5))
aa

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

#### <div class= "alert alert-warning">Difference between reshape() & resize()</div> 

- <mark>reshape():</mark>
    
    1. modifies shape of an array
    2. doesn't return the orignal array, only the changed array

- <mark>resize():</mark>

    1. modifies array shape and adds a copy orignal array if necessary
    2. resize method returns nothing and directly changes the orignal array