# <div class="alert alert-success" >(6). Stacking (part-1)
    
Stacking is the concept of joining same dimension arrays in Numpy. Stacking is done along a new axis and leads to increased customization of an array. We can combine the stack function with other functions to further increse its capability.

Stacking can be done along three dimensions/axis:
- Along the Rows i.e axis = 0 (Vertical stacking)
- Along the columns i.e axis = 1 (Horizontal stacking)
- Along the depth i.e axis = 0  (Depth stacking)
Other stacking includes row stacking (same as Vertical stacking) and column stacking (same as horizontal stacking)
    
<div class = "alert alert-warning"> In 3D arrays axis = 0 represents depth, axis = 1 represents rows and axis = 2 represents columns </div>    

In [2]:
import numpy as np

#### <div class= "alert alert-info"> The stack function: stack()
    
 To join two arrays along the second axis, which would result in putting one over the otheri.e stacking, we pass a sequence of arrays (that we want to join) to the <span style="color:red">stack()</span> method anlon with the axis.<mark> if the axis is not explicitly passed it is taken as 0</mark>.
    
<span style="color:red">stack(</span> (array1 , array2), axis = 0/1/2  <span style="color:red">)</span>
- stack() stacks array2 after array1, vertically, horizontally or depth wise depending on the axis

#### <div class= "alert alert-danger">1D arrays stacking    
1D arrays stacking results in a 2D array so we can stack it row or column wise    </div>

In [4]:
a = np.array([1,2,3])   # defining 1D arrays
b = np.array([4,5,6])
print("a = ",a)
print("b = ",b)

a =  [1 2 3]
b =  [4 5 6]


In [89]:
print("a's shape = ",a.shape,'\n')
print("b's shape = ",b.shape)

a's shape =  (3,) 

b's shape =  (3,)


######  The stack function along axis = 1 (column wise)

In [38]:
arr1 = np.stack((a,b), axis = 1)  # stacking 1D arrays column wise resulted in a 2D array
arr1

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
arr1.shape        # arr1 has 3 rows and 2 columns

(3, 2)

In [19]:
arr1[0,:]       # arr1's row 0

array([1, 4])

In [20]:
arr1[1,:]      # arr1's row 1

array([2, 5])

In [26]:
arr1[2,:]       # arr1's row 2

array([3, 6])

In [27]:
arr1[:,0]       # arr1's column 0

array([1, 2, 3])

In [28]:
arr1[:,1]       # arr1's column 1

array([4, 5, 6])

<mark>stacking 1D arrays (a & b) column wise (axis = 1) resulted in a 2D array 'arr1' =[[ a b]] (ie arr1[c0]=a & arr1[c1]=b)</mark>

###### The stack function along axis = 0 (row wise)

In [29]:
arr0 = np.stack((a,b)) # axis by default is 0 axis ie row wise stacking
arr0

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr0.shape   # arr0 has 2 rows and 3 columns

(2, 3)

In [33]:
arr0[0,:]           # arr0's row 0

array([1, 2, 3])

In [34]:
arr0[0,:]           # arr0's row 1

array([1, 2, 3])

In [35]:
arr0[:,0]           # arr0's column 0

array([1, 4])

In [36]:
arr0[:,1]           # arr0's column 1

array([2, 5])

In [37]:
arr0[:,2]           # arr0's column 2

array([3, 6])

<mark>stacking 1D arrays (a & b) row wise (axis = 0) resulted in a 2D array 'arr0' =[[ a b]] (ie arr0[r0]=a & arr0[r1]=b)</mark>

#### <div class= "alert alert-danger">2D arrays stacking
2D arrays stacking results in a 3D array so we can stack it row, column or depth wise    

In [76]:
c = np.array([[1,2],[3,4], [5,6]])
d = np.arange(7,13).reshape(3,2)
print('c = ',c,'\n')
print('d = ',d)

c =  [[1 2]
 [3 4]
 [5 6]] 

d =  [[ 7  8]
 [ 9 10]
 [11 12]]


In [88]:
print("c's shape = ",c.shape,'\n')
print("d's shape = ",d.shape)

c's shape =  (3, 2) 

d's shape =  (3, 2)


###### The stack function along axis = 0 (depth wise)

In [77]:
brr0 = np.stack((c,d), axis = 0)    # brr0 = np.stack((c,d)) will also do
brr0

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [78]:
brr0.shape         # stacking two 2D arrays results in a 3D array 

(2, 3, 2)

In [79]:
brr0[0,:,:]       # brr0's depth 0

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
brr0[1,:,:]       # brr0's depth 1

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

<mark>stacking 2D arrays (c & d) depth wise (axis = 0) resulted in a 3D array 'brr0' =[ [[c]], [[d]] ] (ie brr0[d0] = c & brr0[d1] = d)</mark>

###### The stack function along axis = 1 (row wise)

In [81]:
brr1 = np.stack((c,d), axis = 1)    
brr1

array([[[ 1,  2],
        [ 7,  8]],

       [[ 3,  4],
        [ 9, 10]],

       [[ 5,  6],
        [11, 12]]])

In [82]:
brr1.shape         # stacking two 2D arrays results in a 3D array 

(3, 2, 2)

In [83]:
brr1[0,:,:]       # brr1's depth 0

array([[1, 2],
       [7, 8]])

In [84]:
brr1[1,:,:]       # brr1's depth 1

array([[ 3,  4],
       [ 9, 10]])

In [85]:
brr1[2,:,:]       # brr1's depth 2

array([[ 5,  6],
       [11, 12]])

<mark>stacking 2D arrays (c & d) row wise (axis = 1) resulted in a 3D array 'brr1' =[ [[ c[r0] , d[ro] ]], [[ c[r1] , d[r1]  ]] , [[ c[r2] , d[r2] ]]] (ie brr1[d0] = c[r0] & d[r0] , brr1[d1] = c[r1] & d[r1] and brr1[d2] = c[r2] & d[r2])</mark>


<mark> 2D stacking row wise: depth = rows of c/d (as both are of same shape)</mark>

###### The stack function along axis = 2 ( column wise)

In [90]:
brr2 = np.stack((c,d), axis = 2) 
brr2

array([[[ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10]],

       [[ 5, 11],
        [ 6, 12]]])

In [91]:
brr2.shape   # 2D stacking column wise: depth = rows of c/d (as both are of same shape)

(3, 2, 2)

In [92]:
brr2[0,:,:]         

array([[1, 7],
       [2, 8]])

In [95]:
brr2[1,:,:]         

array([[ 3,  9],
       [ 4, 10]])

In [96]:
brr2[2,:,:]         

array([[ 5, 11],
       [ 6, 12]])

<mark>stacking 2D arrays (c & d) column wise (axis = 2) resulted in a 3D array:
'brr2' = [ [[ c[C0=r0] , d[C0=r0] ]], [[ c[C1=r1] , d[C1=r1]  ]] , [[ c[C2=r2] , d[C2=r2] ]]]

(ie brr2[d0] = C0=c[r0] & C0=d[r0] , brr2[d1] = C1=c[r1] & C1=d[r1] and brr2[d2] = C2=c[r2] & C2=d[r2])</mark>

or simply Depth[i]: Colimns[i] = Rows[i]

<mark> 2D stacking column wise: depth = rows of c/d (as both are of same shape)</mark>

#### <div class= "alert alert-danger">3D arrays stacking
    
 3D arrays stacking results in a 4D array, so we can stack it page (4th dim),depyh, row or column wise     

In [103]:
e = np.arange(9).reshape(1,3,3)
f = np.arange(9,18).reshape(1,3,3)
print("e = ",e,"\n")
print("f = ",f)

e =  [[[0 1 2]
  [3 4 5]
  [6 7 8]]] 

f =  [[[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [104]:
print("e's shape = ",e.shape,'\n')
print("f's shape = ",f.shape)

e's shape =  (1, 3, 3) 

f's shape =  (1, 3, 3)


###### The stack function along axis = 0 (page wise)

In [105]:
crr0 = np.stack((e,f))
crr0

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]]],


       [[[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]])

In [68]:
crr0.shape    # stacking 3D arrays results in a 4D array.

# An n-dimensional array is a collection of n-1 dimensional arrays, for n > 0

(2, 1, 3, 3)

<mark>In 4D arrays: (n,d,r,c)  </mark>

- <mark>n = number of 3D arrays (i call it page for sor simplicity) </mark>
- <mark>d = depth of each 3D array </mark>
- <mark>r = rows per depth of each 3D array </mark>
- <mark>c = columns per depth of each 3D array </mark>

In [64]:
crr0[0,:,:,:]           # 1st 3D array of 4D array

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [69]:
crr0[1,:,:,:]           # 2nd 3D array of 4D array

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

<mark>stacking 3D arrays (e & f) page wise (axis = 0) resulted in a 4D array 'crr0' =[ [[[e]]], [[[f]]] ] (ie two 3D arrays on a page, each with depth 1, and rows and columns = (3,3) )</mark>

###### The stack function along axis = 1 (depth wise)

In [106]:
crr1 = np.stack((e,f), axis = 1)
crr1

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]])

In [107]:
crr1.shape

(1, 2, 3, 3)

<mark>stacking 3D arrays (e & f) depth wise (axis = 1) resulted in a 4D array 'crr1' =[ [ [[e ]], [[f]] ] ] (ie 4D array with one 3D array with d0 = e and d1 = f </mark>

###### The stack function along axis = 2 (row wise)

In [108]:
crr2 = np.stack((e,f), axis = 2)
crr2

array([[[[ 0,  1,  2],
         [ 9, 10, 11]],

        [[ 3,  4,  5],
         [12, 13, 14]],

        [[ 6,  7,  8],
         [15, 16, 17]]]])

In [109]:
crr2.shape

(1, 3, 2, 3)

<mark>stacking 3D arrays (e & f) row wise (axis = 2) resulted in a 4D array 'crr2' =[ [ [[e[r0], f[r0] ]], [[e[r1], f[r1]], [[e[r2], f[r2]] ] ] (ie 4D array with one 3D array with depth di: ci = e[ri] & f[ri]  </mark>

<mark>  4D array with one 3D array whose di: ri = e[ri] & f[ri] </mark>

<mark>  rows per depth = 2 (always)</mark>

###### The stack function along axis = 3(column wise)

In [110]:
crr3 = np.stack((e,f), axis = 3)
crr3

array([[[[ 0,  9],
         [ 1, 10],
         [ 2, 11]],

        [[ 3, 12],
         [ 4, 13],
         [ 5, 14]],

        [[ 6, 15],
         [ 7, 16],
         [ 8, 17]]]])

In [111]:
crr3.shape

(1, 3, 3, 2)

stacking 3D arrays (e & f) column wise (axis = 3) resulted in a 4D array 'crr3' =[ [ [[C0 = e[r0], C2 = f[r0 ]], [[C1 = e[r1], C1 = f[r1]], [[C0 = e[r2],C1 = f[r2]] ] ] (ie 4D array with one 3D array with depth di: ci = e[ri] & f[ri]  </mark>

<mark>  4D array with one 3D array whose di: ci = e[ri] & f[ri] </mark>

<mark>  columns per depth = 2 (always)</mark>

#### <div class="alert alert-success" > summary
    
            1D stack
    
| Axis | Discription of resultant array         |
|------|----------------------------------------|
| 0    | 2D array whose rows: ri = array1[ri] & array2[ri] |    
| 1    | 2D array whose columns: ci = array1[ri] & array2[ri] |    

            2D stack  

| Axis | Discription of resultant array|
|------|----------------------------------------|
| 0    |  3D array whose depths are the 2D arrays|    
| 1    |  3D array with depths = rows of array1or2. d0 has array1&2's row0  and d1 has array1&2's row1|
| 2    |  3D array with Depth[i]: Colimns[i] = Rows[i]|   
    
            3D stack

| Axis | Discription of resultant array|
|------|----------------------------------------|
| 0    |   4D array with two 3D arrays : array=[ [[[array1]]], [[[array2]]] ] |    
| 1    |   4D array with one 3D array whose d0 = e and d1 = f|
| 2    |   4D array with one 3D array whose di: ri = array1[ri] & array2[ri] |
| 3    |   4D array with one 3D array whose di: ci = array1[ri] & array2[ri]|        