# <div class="alert alert-success" > (5). Numpy numerical types</div>

Default datatype of Python is float thus  , default datatype of array is also float.cNumbers in array can be integer type, float type and complex type (string type array not used in DS). These are not enough for scientific computing that is why Numpy 
has alot of more data types with varying precision (depending on memory requirment).

Most of Numpy numerical types ends with a number (e.g int64), this number indicates the number of bits associated with the type. Following are the numerical types in Numpy:

<div class = "alert alert-warning"> 
    
    
| Type | Discription|
|------|----------------------------------------|
| bool | boolean (True or False) stored as a bit|    
| inti | platform integer (normally either int 32 or int64)|
| int8 | byte (-128 to 127)|
| int16 | integer (-32768 to 32767) |
| int32 | integer (-2**31 to 2**(31-1)) |
| int64 | integer (-2**63 to 2**(63-1))|        
| unit8 | unsigned integer (0 to 255| 
| unit16 | unsigned integer (0 to 65535)|         
| unit32 | unsigned integer (0 to 2**(32-1))|
| unit64 | unsigned integer (0 to2**(64-1))|  
| float16 |half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
| float32 |single precision float: sign bit, 8 bits exponent, 32 bits mantissa| 
| float64 / float |double precision float: sign bit, 11 bits exponent, 52 bits mantissa|     
| complex64 |complex number, represented by two 32 bits floats(real & imagnary components) 
| complex128 / complex |complex number, represented by two 64 bits floats(real & imagnary components)     
</div>

<div class = "alert alert-warning"> For floating typee, we can request information with <span style="color:red">finfo()</span> function e.g :

In [1]:
import numpy as np

In [2]:
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

For each data type there exist a corrosponding conversion function:

In [12]:
np.float64(42)         # int to float

42.0

In [13]:
np.int8(np.float64(42))     # float to int

42

In [15]:
bool(42)

True

In [16]:
bool(0)

False

In [17]:
np.int8(bool(42))

1

In [18]:
np.int8(bool(0))

0

In [20]:
float(True)

1.0

Many methods have a data type option thats optional e.g np.<span style="color:red">arange(</span> 7 , dtype = np.complex64 <span style="color:red">)</span>

In [25]:
np.arange( 7 , dtype = np.complex64)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j],
      dtype=complex64)

###### <div class = "alert alert-warning">We cant convert complex numbers to int or float and vice versa </div>

#### <div class= "alert alert-info"> Data type objects
    
Data type objects are instances of np.dtype class .Again arrays do have a data type, to be precise every element in a Numpy array has the same  data type. Data type object can tell you the size of the data in bytes using the datatype class attribute <span style="color:red">itemsize</span>. e.g

In [26]:
a = np.arange(3)

In [27]:
a.dtype

dtype('int32')

In [28]:
a.itemsize

4

#### <div class= "alert alert-info"> Character codes
    
Character codes are included for backwords compatibility with numerics. Numerics is the predecessor of Numpy. Their use isn't recommended but are provided here as they do popup in several places. We should instead use the dtype objects. Below table shows character codes:
    
| Type                   | Character code |
|------------------------|----------------|
| Intiger                | i              |    
| Insigned integer       | u              |
| Single precision float | f              |
| Double precision float | d              |
| Boolean                | b              |
| Complex                | D              |        
| String                 | S              | 
| Unicode                | U              |         
| Void                   | V              |


In [30]:
b = np.arange(3,dtype = "f")
b

array([0., 1., 2.], dtype=float32)

In [32]:
c = np.arange(3,dtype = "D")
c

array([0.+0.j, 1.+0.j, 2.+0.j])

In [35]:
print("b's datatypr = ",b.dtype)
print("c's datatypr = ",c.dtype)

b's datatypr =  float32
c's datatypr =  complex128


###### <div class = "alert alert-warning">To create arrays with defined data types, use <span style="color:red">arange()</span> or <span style="color:red">array()</span> functions. This function can take an optional argument (dtype) that allows you to define the data type of an array. 

In [37]:
d = np.array([1,2,3,4,5],dtype = "S")
d

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [38]:
np.array([1,2,3,4,5],dtype = "U")

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [39]:
np.array([1,2,3,4,5],dtype = "i")

array([1, 2, 3, 4, 5], dtype=int32)

In [40]:
np.array([1,2,3,4,5],dtype = "f")

array([1., 2., 3., 4., 5.], dtype=float32)

In [42]:
np.array([1,2,3,4,5],dtype = "d")

array([1., 2., 3., 4., 5.])

In [43]:
np.array([1,2,3,4,5],dtype = "b")

array([1, 2, 3, 4, 5], dtype=int8)

In [44]:
np.array([1,2,3,4,5],dtype = "D")

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

#### <div class= "alert alert-info"> Coverting data type of existing arrray
    
Best way to convert the data tyoe of an array is to make a copy of the array with the <span style="color:red">astype()</span> method.
    
<span style="color:red">astype()</span> function creates a copy of the array and allows you to specify the data type as a parameter. The data type can be specified as strings, like: 'f' for float  'i' for intiger, etc or you can use the data type directly like 'float' , 'int' , etc.

In [48]:
a

array([0, 1, 2])

In [51]:
a.dtype

dtype('int32')

In [49]:
a.astype('f')

array([0., 1., 2.], dtype=float32)

In [52]:
a.astype(float)

array([0., 1., 2.])

In [56]:
a.astype(bool)

array([False,  True,  True])