# <div class="alert alert-success" >(2) Array indexing
    
Array indexing means accessing array elements. in Numpy indexing an array follows the same ryles as python list indexing
   
- Positive indexing:is from 0 to [n-1]. with first element at index 0 and last element at indes[n-1]. n is the size of an array
- Negative indexing:is from [-n] to [-1]. with first element at index [-n] and last element at indes[-1]. n is the size of an array

In [1]:
import numpy as np
a = np.arange(1,11)
b = np.arange(1,11).reshape(2,5)
c = np.arange(1,13).reshape(2,2,3)

#### <div class= "alert alert-info">Vector Indexing:

In [2]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a[0]        # element at index 0

1

In [4]:
a[3]        # element at index 3

4

In [5]:
a[9]        # element at index 9

10

In [6]:
a[-10]         # first element of an array

1

In [7]:
a[-9]

2

In [8]:
a[-8]

3

In [9]:
a[-3]

8

In [10]:
a[-2]

9

In [11]:
a[-1]              # last element of an array

10

#### <div class= "alert alert-info">Matrix Indexing:
    
 Matrix indixing require row and columns ie matrix[r,c] or matrix[r][c].
    
 [ [r0 c0-1],[r1 c0-1] ]2x2 

In [12]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
b[0,0]         # element @ r0,c0 

1

In [14]:
b[0][1]

2

In [15]:
b[0,2]         # element @ r0,c2 

3

In [16]:
b[0,4]         # element @ r0,c4 

5

In [17]:
b[1,0]         # element @ r1,c0 

6

In [18]:
b[1,2]         # element @ r1,c2 

8

In [19]:
b[1,4]         # element @ r1,c4 

10

In [20]:
b[1,3]         # element @ r1,c3

9

### <div class= "alert alert-info">Cube Indexing:

Matrix indixing require depth, row and columns ie matrix[d,r,c] or matrix[d][r][c]
    
[ [[d0 r0-1 c0-2]],[[d0 r0-1 c0-2]] ]2x2x3 

In [21]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
c[0,0,1]           # element @ d0 r0 c1

2

In [23]:
c[0][1][2]          # element @ d0 r1 c2

6

In [24]:
c[1,0,1]           # element @ d1 r0 c1

8

In [25]:
c[1,1,1]           # element @ d1 r1 c1

11

In [26]:
c[1,1,2]           # element @ d0 r0 c1

12

# <div class="alert alert-success" >Array slicing

    Slicing is indexing but it selects a range of elements. Like Python we use : for slicing.

#### <div class= "alert alert-info">Vector Slicing:
    
- 1D array is sliced like:-   array_name[a:b:n]. It starts slicing array_name from 'a' to [b-1] with a jump on n 
   

In [27]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
a[3:6]      # slice array from index 3 to 5

array([4, 5, 6])

In [29]:
a[:6]      # slice array from index 0 to 5

array([1, 2, 3, 4, 5, 6])

In [30]:
a[:]      # slice array from index 0 to 9 ie all array elements

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
a[1: ]      # slice array from index 1 to 9 (till end)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a[0:7:2]      # slice array from index 0 to 6 with a jump of 2

array([1, 3, 5, 7])

In [33]:
a[: :2]      # slice array from index 0 to 9 with a jump of 2

array([1, 3, 5, 7, 9])

In [34]:
a[3::3]      # slice array from index 3 to 9 with a jump of 3

array([ 4,  7, 10])

#### <div class= "alert alert-info">Matrix Slicing:
    
- 2D array is sliced like:-   array_name[ra:rb:rn , ca:cb,rn]. It starts slicing array_name rows from 'ra' to [rb-1] with a jump on rn and columns from 'ca' to [cb-1] with a jump on cn.
    
<div class="alert alert-warning"> If either row or column is fixed while the other is sliced we get 1D array </div>

In [35]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
b[1:2,2:4]   # slicse  r1 from c2-3 

array([[8, 9]])

In [37]:
b[0:2,3:5]   # slicse from r0-1 to c3-4 

array([[ 4,  5],
       [ 9, 10]])

In [38]:
b[::2,1:3]   # slicse from r0-1 with jump 2 (ie just r0) and c1-2

array([[2, 3]])

<mark> When row is fixed and column is sliced or vie versa it results in 1D array as below: </mark>

In [39]:
b[1,1:66]   # slicse  r1 from c1-4 (if index out of range it slice till end)

array([ 7,  8,  9, 10])

In [40]:
b[0:3,3]

array([4, 9])

In [41]:
b[:,::2]   # slicse from r0-1 and c1-4 with jump 2 

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [42]:
b[:,::-2]   # slicse from r0-1 and c1-4 with jump -2 

array([[ 5,  3,  1],
       [10,  8,  6]])

In [43]:
b[::-1,::-1]   # slicse from r0-1 with jump -1 and c1-4 with jump -1

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

#### <div class= "alert alert-info">Cube Slicing:
    
- 3D array is sliced like:-   array_name[da:db:dn ,  ra:rb:rn , ca:cb,rn]. It starts slicing array_name depth from 'da' to [db-1] with a jump on dn , rows from 'ra' to [rb-1] with a jump on rn and columns from 'ca' to [cb-1] with a jump on cn.
    
<div class="alert alert-warning"> 
    
  - If depth is sliced while rows & columns are fixed we get 1D array [Depth slicing]
    
  - If row is sliced while depth & columns are fixed we get 1D array  [Row slicing]
    
  - If column is sliced while rows & depth are fixed we get 1D array  [Column slicing] 
    
  - If depth & row is sliced while column is fixed we get 2D array
    
  - If depth & column is sliced while row is fixed we get 2D array
</div>

In [44]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

##### 1D Slicing

In [46]:
c[1:2,1,2]             # Slices c's depth from d1-2 (ie d1 ) for r1 &c2  [depth slicing]

array([12])

In [47]:
c[1,:2,1]              # Slices c's row from r0-2 (ie r0 & r1 ) for d1 &c1  [row slicing] 

array([ 8, 11])

In [54]:
c[1,1,0:3:2]            # Slices c's columns from c0-1 with  jump 2 for d1 &r1  [column slicing]

array([10, 12])

<div class ="alert alert-warning"> In a cube array depth is axis = 0 and row is axis = 1 and col is axis = 2? </div>

##### 2D Slicing

In [56]:
c[:,1:2,2]            # Slices c's depth and row from  d0-1, r1-2 (ie r1) for c2

array([[ 6],
       [12]])

<mark> c[0] or c[1] for 3D is basically depth slicing: </mark>

In [68]:
c[0]         # slicing d0 for all rows and columns

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
c[1]         # slicing d1 for all rows and columns

array([[ 7,  8,  9],
       [10, 11, 12]])

In [70]:
c[: : -1]          # reverses depths

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [71]:
c[: : -1, : : -1,:]      # reverses depths and rows per depth

array([[[10, 11, 12],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [ 1,  2,  3]]])

In [72]:
c[: : -1, : : -1,: : -1]      # reverses depths, columns per depth and rows per depth

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [57]:
c[:,0,0:3:2]            # Slices c's depth and columns  from  d0-1, c0-2 with jump 2 for r0

array([[1, 3],
       [7, 9]])

In [58]:
c[1,:,0:3:2]            # Slices c's rows and columns from  r0-1, c0-2 with jump 2 for d1

array([[ 7,  9],
       [10, 12]])

##### 3D Slicing

In [59]:
c[1:,:,1:3]           # Slicing c's depth d1, row from r0-1 and column from c1-2

array([[[ 8,  9],
        [11, 12]]])

##### Ellipsis function (...)

Ellipsis reffers to multiple dimensions at once i.e for c[:,:,1] we can simply write c[...,1]. 
Similarly c[0,:,:] = c[0,...]

In [60]:
c[:,:,1]

array([[ 2,  5],
       [ 8, 11]])

In [61]:
c[...,1]

array([[ 2,  5],
       [ 8, 11]])

In [62]:
c[1,:,:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [63]:
c[1,...]

array([[ 7,  8,  9],
       [10, 11, 12]])

<mark> ... works for consective axis i.e axis 0,1 or 1,2 </mark>