# <div class="alert alert-success" > (4). Difference between copy and view of an array</div>

### <div class = "alert alert-warning"> Copy </div>
    1. copy gives a new array 
    2. copy owns the data 
    3. any changes made to copy array elements will not affect the orignal array elements and vice versa 
    
### <div class = "alert alert-warning"> View </div>
    1.view just reffer to the orignal array
    2. view doesn't owns the data 
    3. any changes made to view array elements will affect the orignal array elements and vice versa 

In [1]:
import numpy as np


#### <div class= "alert alert-info"> Array Copy

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr_copy = arr.copy()
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### changes in array copy and orignal array:

In [4]:
arr[0] = 10                        # change to orignal array
arr  

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [5]:
arr_copy                           # change to orignal array didnt change array copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr_copy[4] = 999                  # change to  array copy
arr_copy

array([  0,   1,   2,   3, 999,   5,   6,   7,   8,   9])

In [7]:
arr                               # change to array copy didnt change the orignal array 

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

#### <div class= "alert alert-info"> Array View

In [8]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr_view = arr.view()
arr_view

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### changes in array view and orignal array:

In [10]:
arr[3] = 8888                     # change to orignal array
arr

array([   0,    1,    2, 8888,    4,    5,    6,    7,    8,    9])

In [11]:
arr_view                           # change to orignal array elements did change array view

array([   0,    1,    2, 8888,    4,    5,    6,    7,    8,    9])

In [12]:
arr_view[4] = -3                # change to  array view
arr_view

array([   0,    1,    2, 8888,   -3,    5,    6,    7,    8,    9])

In [13]:
arr                             # change to array view did change the orignal array 

array([   0,    1,    2, 8888,   -3,    5,    6,    7,    8,    9])

#### <div class= "alert alert-warning">checking if array owns its data:</div> 

Copy owns its data and view doesn't we cah check this using Numpy array attribute <span style="color:red">base</span>. base returns " None" if array owns its data or returns the array if the array doesn't owns its data


In [15]:
print("copy of array,arr_copy: ",arr_copy.base)

copy of array,arr_copy:  None


In [16]:
print("view of array,arr_view: ",arr_view.base)

view of array,arr_view:  [   0    1    2 8888   -3    5    6    7    8    9]
